# Generated by Django 5.0.1 on 2024-02-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serialize', '0002_rename_dept_students_dept_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='dept_id',
            new_name='dept_no',
        ),
    ]
