# Generated by Django 5.0.1 on 2024-02-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serialize', '0003_rename_dept_id_students_dept_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='dept_no',
            new_name='dept',
        ),
    ]
